name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3

    - name: Install dependencies
      run: npm ci

    - name: Bump version and push tag
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        npm version patch -m "Bump to %s"
        git push

    - name: Build app
      run: npm run build

    - name: Get version
      id: packagejson
      uses: martinbeentjes/npm-get-version-action@v1.1.0

    - name: Create Release
      run: zip -j -r sendToKodi-${{ steps.packagejson.outputs.current-version }}.zip build/*
      id: create_release

    - name: Upload Release
      uses: actions/upload-artifact@v3
      with:
        name: sendToKodi-${{ steps.packagejson.outputs.current-version }}
        path: sendToKodi-${{ steps.packagejson.outputs.current-version }}.zip