name: Bump Version

on: workflow_call
jobs:
  release:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.bump.outputs.version }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Bump version
      id: bump
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        echo "version=$(npm version patch -m "Bump to %s")" >> "$GITHUB_OUTPUT"

