name: Bump Version

on: workflow_call
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Bump version
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        echo "VERSION=$(npm version patch -m "Bump to %s")" >> $GITHUB_ENV
        git push

    outputs:
      version: ${{ env.VERSION }}