name: Manual Release

on: [workflow_dispatch]
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3

    - name: Install dependencies
      run: npm ci

    - name: Bump version
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        npm version patch -m "Bump to %s"
        git push

    - name: Build app
      run: npm run build

    - name: Get version
      id: packagejson
      uses: martinbeentjes/npm-get-version-action@v1.1.0

    - name: Get last release tag
      id: last_release
      run: |
        echo "::set-output name=tag::$(curl --silent "https://api.github.com/repos/firsttris/chrome.sendtokodi/releases/latest" | jq -r .tag_name)"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Get SHA of last release
      id: last_release_sha
      run: |
        echo "::set-output name=sha::$(git rev-list -n 1 ${{ steps.last_release.outputs.tag }})"
    
    - name: Get commits since last release
      id: commits
      run: |
          echo "::set-output name=list::$(git log --pretty=format:"%h %s" ${{ steps.last_release_sha.outputs.sha }}..HEAD)"

    - name: Create Release
      run: cd dist && zip -r ../sendToKodi-${{ steps.packagejson.outputs.current-version }}.zip *
      id: create_release

    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: 'sendToKodi-${{ steps.packagejson.outputs.current-version }}.zip'
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ steps.packagejson.outputs.current-version }}
        body: |
          Changes:
          ${{ steps.commits.outputs.list }}