name: Release Addon

on: [workflow_dispatch]
jobs:
  bumpVersion:
    uses: ./.github/workflows/bump_version.yml

  releaseChrome:
    needs: bumpVersion
    uses: ./.github/workflows/release_chrome.yml
    with:
      version: ${{ needs.bumpVersion.outputs.version }}

  releaseFirefox:
    needs: bumpVersion
    uses: ./.github/workflows/release_firefox.yml
    with:
      version: ${{ needs.bumpVersion.outputs.version }}